import './ui/global.css'
import Image from 'next/image';
import Navbar from '../Components/Navbar';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by mahya',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body>
      <Navbar/>
     <Image priority={true} className='left-leaf z-0' src='/leaf.jpg' width='75'  height='70' alt='leaf' />
     <Image   priority={true} className='right-leaf z-0' src='/leaf.jpg' width='75' height='70' alt='leaf' />
        {children}
     
        </body>
    </html>
  )
}
